name: Battery SOC Page Add-on
version: "1.0.10"
slug: battery_soc_page
description: Serves a web page with battery SOC data via Cloudflare Tunnel and updates via JSON POST
url: "https://example.com"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Local web server (for testing; main access via Cloudflare domain)
options:
  tunnel_token: ""
schema:
  tunnel_token: str
